---
#################################################
# Openshift Install Prep
# Author: B.F. Taljaard
# Date: 27 Feb 2019
#################################################

# Need to fix a few things on the hosts before we can run any installation tasks


# Run fix script on all hosts
- name: Fix host configuration to prepare for install
  hosts: nodes
  tasks:
    - name: Enable all required redhat repositories
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      with_items:
      - "rhel-7-server-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-7-server-ose-3.11-rpms"
      - "rhel-7-server-ansible-2.6-rpms"
    - name: Add proxy configuration
      lineinfile:
        path: /etc/profile.d/proxy.sh
        create: yes
        state: present
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      with_items:
        - { regex: '^export https_proxy', line: 'export https_proxy=http://172.23.29.156:3128'  }
        - { regex: '^export http_proxy', line: 'export http_proxy=http://172.23.29.156:3128'  }
        - { regex: '^export no_proxy', line: 'export no_proxy=.csa.internal,.libgbl.biz'  }
    - name: Configure /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
      with_items:
        - { regex: '^172.23.48.147', line: '172.23.48.147 lg-l-n-msa00001'  }
        - { regex: '^172.23.48.142', line: '172.23.48.142 lg-l-n-msa00002'  }
        - { regex: '^172.23.48.137', line: '172.23.48.137 lg-l-n-msa00003'  }
        - { regex: '^172.23.48.223', line: '172.23.48.223 lg-l-n-msa00004'  }
        - { regex: '^172.23.48.229', line: '172.23.48.229 lg-l-n-msa00005'  }
        - { regex: '^172.23.48.230', line: '172.23.48.230 lg-l-n-msa00006'  }
        - { regex: '^172.23.48.243', line: '172.23.48.243 lg-l-n-msa00007'  }
        - { regex: '^172.23.48.244', line: '172.23.48.244 lg-l-n-msa00008'  }
        - { regex: '^172.23.49.161', line: '172.23.49.161 lg-l-n-msa00009'  }
        - { regex: '^172.23.49.162', line: '172.23.49.162 lg-l-n-msa00010'  }
        - { regex: '^172.23.49.163', line: '172.23.49.163 lg-l-n-msa00011'  }
        - { regex: '^172.23.49.164', line: '172.23.49.164 lg-l-n-msa00012'  }
        - { regex: '^172.23.30.14', line: '172.23.30.14 nlcsapvcp001.csa.internal'  }




#     - name: Resize /var/log LVM
#       lvol:
#         vg: vgroot
#         lv: lv_log
#         size: 10g
#         resizefs: true
#     - name: Resize /var LVM
#       lvol:
#         vg: vgroot
#         lv: lv_var
#         size: 8g
#         resizefs: true

# # Remove some default disks and create new ones
# - name: Create master node host storage
#   hosts: masters
#   tasks:
#     - name: Unmount apps LVM and remove from fstab
#       mount: 
#         path: /u01/appl
#         src: /dev/mapper/vgapp-lv_app
#         state: absent
#     - name: Delete existing apps LVM
#       lvol:
#         vg: vgapp
#         lv: lv_app
#         state: absent
#         force: yes
#     - name: Create openshift etcd LVM
#       lvol:
#         vg: vgapp
#         lv: lv_etcd
#         size: 20g
#         state: present
#     - name: Create openshift emptyDir LVM
#       lvol:
#         vg: vgapp
#         lv: lv_emptyDir
#         size: 40g
#         state: present
#         # force: yes
#     - name: Format etcd LVM
#       filesystem:
#         fstype: xfs
#         dev: /dev/mapper/vgapp-lv_etcd
#     - name: Format emptyDir LVM
#       filesystem:
#         fstype: xfs
#         dev: /dev/mapper/vgapp-lv_emptyDir
#     - name: Mount etcd LVM
#       mount:
#         path: /var/lib/etcd
#         src: /dev/mapper/vgapp-lv_etcd
#         fstype: xfs
#         opts: defaults
#         state: mounted
#     - name: Mount emptyDir LVM
#       mount:
#         path: /var/lib/origin/openshift.local.volumes
#         src: /dev/mapper/vgapp-lv_emptyDir
#         fstype: xfs
#         opts: grpquota
#         state: mounted



# - name: Create infra and app node host storage
#   hosts: infras, apps
#   tasks:
#     - name: Unmount apps LVM and remove from fstab
#       mount: 
#         path: /u01/appl
#         src: /dev/mapper/vgapp-lv_app
#         state: absent
#     - name: Delete existing apps LVM
#       lvol:
#         vg: vgapp
#         lv: lv_app
#         state: absent
#         force: yes
#     - name: Create openshift emptyDir LVM
#       lvol:
#         vg: vgapp
#         lv: lv_emptyDir
#         size: 40g
#         state: present
#         # force: yes
#     - name: Format emptyDir LVM
#       filesystem:
#         fstype: xfs
#         dev: /dev/mapper/vgapp-lv_emptyDir
#     - name: Mount emptyDir LVM
#       mount:
#         path: /var/lib/origin/openshift.local.volumes
#         src: /dev/mapper/vgapp-lv_emptyDir
#         fstype: xfs
#         opts: grpquota
#         state: mounted

# # Install docker and configure storage
# - name: Configure Docker
#   hosts: nodes
#   environment:
#      PATH: /usr/sbin:{{ ansible_env.PATH }}
#   tasks:
#     - name: Install Docker
#       yum:
#         name:
#           - docker-1.13.1
#         state: present 
#     - name: Configure storage volume group
#       lineinfile:
#         path: /etc/sysconfig/docker-storage-setup
#         state: present
#         regexp: '^VG='
#         line: 'VG=vgapp'
#     - name: Configure storage driver
#       lineinfile:
#         path: /etc/sysconfig/docker-storage-setup
#         state: present
#         regexp: '^STORAGE_DRIVER='
#         line: 'STORAGE_DRIVER=devicemapper'
#     - name: Run docker storage setup
#       command: /usr/bin/docker-storage-setup
#     - name: Configure docker logging
#       lineinfile:
#         path: /etc/sysconfig/docker
#         state: present
#         regexp: '^OPTIONS='
#         line: "OPTIONS='--selinux-enabled --log-driver=json-file --log-opt max-size=1M --log-opt max-file=3 --signature-verification=false'"
      

