---
#################################################
# Openshift One-click install
# Author: B.F. Taljaard
# Date: 18 Feb 2019
#################################################

# Create project template to ensure projects get default network policies and limits
- name: Load new project template
  hosts: localhost
  tasks:
    - name: Load new project template
      shell: oc apply -n default -f /home_ldap/btaljaard/ocp_311_install/resources/project_template_multi_tenancy.yaml

# Configure masters to use the new project template
- name: Configure openshift to use the new template
  hosts: masters
  tasks:
    - name: Add the new project template
      lineinfile:
        path: /etc/origin/master/master-config.yaml
        state: present
        regexp: "^  projectRequestTemplate:"
        replace:  "  projectRequestTemplate: 'default/project-request-multi-tenant'"
    - name: Restart master services 
      command: /usr/local/bin/master-restart "{{ item }}"
      with_items:
      - "api"
      - "controllers"
      register: result
      until: result.rc == 0
