---
#################################################
# Openshift Install Prep
# Author: B.F. Taljaard
# Date: 27 Feb 2019
#################################################

# Need to fix a few things on the hosts before we can run any installation tasks

# Run fix script on all hosts
- name: Run fix script
  hosts: nodes
  tasks:
    - name: Run fix script
      script: ../scripts/fix_host_config_np.sh
      