---
#################################################
# Openshift Install Prep
# Author: B.F. Taljaard
# Date: 27 Feb 2019
#################################################

# Need to fix a few things on the hosts before we can run any installation tasks


# Run fix script on all hosts
- name: Fix host configuration to prepare for install
  hosts: nodes
  tasks:
    - name: Enable all required redhat repositories
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      with_items:
      - "rhel-7-server-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-7-server-ose-3.11-rpms"
      - "rhel-7-server-ansible-2.6-rpms"
    - name: Add https proxy configuration
      lineinfile:
        path: /etc/profile.d/proxy.sh
        create: yes
        state: present
        regex: '^export https_proxy'
        line: 'export https_proxy=http://172.23.29.156:3128'
    - name: Add http proxy configuration
      lineinfile:
        path: /etc/profile.d/proxy.sh
        create: yes
        state: present
        regex: '^export http_proxy'
        line: 'export http_proxy=http://172.23.29.156:3128'

