---
#################################################
# Openshift One-click install
# Author: B.F. Taljaard
# Date: 18 Feb 2019
#################################################

# Set GUID on all machines
- name: Set GUID on all machines
  hosts: all,localhost
  tasks:
    - name: Get GUID
      shell: hostname | cut -d"." -f2
      register: GUID
      ignore_errors: True
    - name: Add GUID export to bashrc
      lineinfile:
        path: $HOME/.bashrc
        line: export GUID={{ GUID['stdout'] }}


# Check Docker
- name: Ensure docker is installed
  hosts: nodes
  tasks:
    - name: Docker is installed
      yum:
        name:
          - docker-1.13.1
        state: present

# Check NFS
- name: Verify NFS Shared Volumes
  hosts: nfs
  tasks:
    - name: Check NFS share exists
      shell: exportfs|grep /srv/nfs

# Install openshift-ansible on bastion
- name: Install openshift packages
  hosts: localhost
  tasks:
    - name: openshift packages are present
      yum:
        name:
          - openshift-ansible
          - atomic-openshift-clients
        state: present


# Replace ansible hosts file
- name: Generate new ansible inventory file
  hosts: localhost
  tasks:
    - name: Copy ansible hosts template file into place
      copy:
        src: /root/rh_adv_deployment_homework/ocp_inventory
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: 0644
        backup: no
    - name: Replace GUID in hosts file
      replace:
        path: /etc/ansible/hosts
        regexp: 'GUID'
        replace: "{{ GUID['stdout'] }}"
    - name: Reload new inventory file
      meta: refresh_inventory