---
#################################################
# Openshift One-click install
# Author: B.F. Taljaard
# Date: 18 Feb 2019
#################################################

# Setup NFS volumes on Support server
- name: Configure NFS disks
  hosts: nfs
  tasks:
    - name: Creating NFS disks for Persistent Volumes
      script: /root/rh_adv_deployment_homework/scripts/create_nfs_pvs.sh
    - name: Restarting NFS Server...
      shell: systemctl restart nfs-server

# Create Persistent Volumes
- name: Create persistent volumes
  hosts: localhost
  tasks:
    - name: Create 5g volume definitions
      script: /root/rh_adv_deployment_homework/scripts/create_5g_pvs.sh
    - name: Create 10g volume definitions
      script: /root/rh_adv_deployment_homework/scripts/create_10g_pvs.sh
    - name: Create persistent volumes on Openshift
      shell: cat /root/pvs/* | oc apply -f -

# Fix persistent volume recycler
- name: Fix persistent volume recycler
  hosts: nodes
  tasks:
    - name: Fix persistent volume recycling
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: Tag ose-recycler
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v1.10.0

# Verify 25 5Gi pvs created set to recycle and 25 10Gi volumes set for reclaim
- name: Verify pvs available
  hosts: localhost
  tasks:
    - name: Verify 5Gi volumes
      shell: (( $(oc get pv|grep Recycle|grep 5Gi|wc -l) == 25 ))
    - name: Verify 10Gi volumes
      shell: (( $(oc get pv|grep pv|grep Retain|grep 10Gi|wc -l) == 25 ))